server:
  port: 8051
  context-path: /

mybatis:
  mapper-locations: classpath*:com/liaoin/mapper/*.xml
  executor-type: simple
  type-aliases-package : com.liaoin.entity
  configuration:
      call-setters-on-nulls: true

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  datasource:
    url: 
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
    initialSize: 2
    maxWait: 60000
    minIdle: 1
  http:
    encoding:
      charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#配置文件路径
project:
  properties:
    files: business/message.properties,business/config.properties

#生产环境中，swagger关闭
swagger:
  switch: false

#日志
logging:
  config: classpath:log/logback-spring.xml
  level:
        com.liaoin: debug
