spring:
  datasource:
#    url: jdbc:mysql://192.168.31.188:3306/zhibo?useunicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    url: jdbc:log4jdbc:mysql://192.168.31.153:3306/zhibo?useunicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: net.sf.log4jdbc.DriverSpy
  redis:
    database: 10
    port: 6379
    host: 192.168.31.153
#    password: 123456
    jedis:
      pool:
        max-idle: 6
        max-active: 32
        max-wait: 100
        min-idle: 4

